// <auto-generated />
using System;
using System.Collections.Generic;
using Loom.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Loom.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008224323_AddConcurrencyTokens")]
    partial class AddConcurrencyTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("Loom.Domain.Entities.CoordinatorWhitelist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.HasKey("Id")
                        .HasName("coordinator_whitelist_pkey");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("coordinator_whitelist_email_key");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("idx_coordinator_whitelist_institution_id");

                    b.ToTable("coordinator_whitelist", (string)null);
                });

            modelBuilder.Entity("Loom.Domain.Entities.Exchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("academic_year");

                    b.Property<int?>("CoordinatorId")
                        .HasColumnType("integer")
                        .HasColumnName("coordinator_id");

                    b.Property<string>("CoordinatorMessage")
                        .HasColumnType("text")
                        .HasColumnName("coordinator_message");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EwpLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ewp_link");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("HomeProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("home_profile_id");

                    b.Property<int>("PartnerInstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("partner_institution_id");

                    b.Property<string>("SemesterType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("semester_type");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.PrimitiveCollection<List<int>>("StudySemesters")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("study_semesters");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("exchange_pkey");

                    b.HasIndex("CoordinatorId")
                        .HasDatabaseName("idx_exchange_coordinator");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("exchange_guid_key");

                    b.HasIndex("HomeProfileId")
                        .HasDatabaseName("idx_exchange_home_profile");

                    b.HasIndex("PartnerInstitutionId")
                        .HasDatabaseName("idx_exchange_partner_institution");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("idx_exchange_student");

                    b.ToTable("exchange", "exchange", t =>
                        {
                            t.HasCheckConstraint("exchange_semester_type_check", "semester_type IN ('Winter', 'Summer', 'Both')");
                        });
                });

            modelBuilder.Entity("Loom.Domain.Entities.ExchangeSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("ChangedById")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ExchangeId")
                        .HasColumnType("integer")
                        .HasColumnName("exchange_id");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phase");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Auto")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("snapshot_pkey");

                    b.HasIndex("ChangedById")
                        .HasDatabaseName("idx_snapshot_changed_by_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_snapshot_created");

                    b.HasIndex("ExchangeId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_snapshot_exchange_created");

                    b.ToTable("snapshot", "exchange", t =>
                        {
                            t.HasCheckConstraint("snapshot_phase_check", "phase IN ('LearningAgreement', 'Recognition')");

                            t.HasCheckConstraint("snapshot_type_check", "type IN ('Auto', 'PreImport')");
                        });
                });

            modelBuilder.Entity("Loom.Domain.Entities.HomeCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("IsvuCode")
                        .HasColumnType("integer")
                        .HasColumnName("isvu_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameEn")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_en");

                    b.HasKey("Id")
                        .HasName("course_pkey");

                    b.HasIndex("IsvuCode")
                        .IsUnique()
                        .HasDatabaseName("idx_home_course_isvu");

                    b.ToTable("course", "home");
                });

            modelBuilder.Entity("Loom.Domain.Entities.HomeCourseGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("slot_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("IsvuCode")
                        .HasColumnType("integer")
                        .HasColumnName("isvu_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameEn")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_en");

                    b.HasKey("Id")
                        .HasName("course_group_pkey");

                    b.HasIndex("CourseTypeId")
                        .HasDatabaseName("idx_home_course_group_slot_type");

                    b.ToTable("course_group", "home");
                });

            modelBuilder.Entity("Loom.Domain.Entities.HomeProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameEn")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_en");

                    b.Property<int>("ProgramId")
                        .HasColumnType("integer")
                        .HasColumnName("program_id");

                    b.HasKey("Id")
                        .HasName("profile_pkey");

                    b.HasIndex("ProgramId")
                        .HasDatabaseName("idx_home_profile_program");

                    b.ToTable("profile", "home");
                });

            modelBuilder.Entity("Loom.Domain.Entities.HomeProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DurationSemesters")
                        .HasColumnType("integer")
                        .HasColumnName("duration_semesters");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameEn")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_en");

                    b.HasKey("Id")
                        .HasName("program_pkey");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("idx_home_program_institution");

                    b.ToTable("program", "home", t =>
                        {
                            t.HasCheckConstraint("program_level_check", "level IN ('Graduate', 'Undergraduate', 'Postgraduate')");
                        });
                });

            modelBuilder.Entity("Loom.Domain.Entities.HomeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("course_group_id");

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Ects")
                        .HasColumnType("integer")
                        .HasColumnName("ects");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("profile_id");

                    b.Property<int>("Semester")
                        .HasColumnType("integer")
                        .HasColumnName("semester");

                    b.Property<int>("SlotPosition")
                        .HasColumnType("integer")
                        .HasColumnName("slot_position");

                    b.Property<int>("SlotTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("slot_type_id");

                    b.HasKey("Id")
                        .HasName("slot_pkey");

                    b.HasIndex("CourseGroupId")
                        .HasDatabaseName("idx_slot_course_group_id");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("idx_slot_course_id");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("idx_home_slot_profile");

                    b.HasIndex("SlotTypeId")
                        .HasDatabaseName("idx_slot_slot_type_id");

                    b.ToTable("slot", "home", t =>
                        {
                            t.HasCheckConstraint("chk_slot_exactly_one_source", "(course_id IS NOT NULL AND course_group_id IS NULL) OR (course_id IS NULL AND course_group_id IS NOT NULL)");

                            t.HasCheckConstraint("slot_semester_check", "semester >= 1 AND semester <= 4");

                            t.HasCheckConstraint("slot_slot_position_check", "slot_position >= 1 AND slot_position <= 30");
                        });
                });

            modelBuilder.Entity("Loom.Domain.Entities.HomeSlotType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NameEn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.HasKey("Id")
                        .HasName("slot_type_pkey");

                    b.ToTable("slot_type", "home");
                });

            modelBuilder.Entity("Loom.Domain.Entities.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ErasmusCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("erasmus_code");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameHr")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_hr");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Partner")
                        .HasColumnName("institution_type");

                    b.HasKey("Id")
                        .HasName("institution_pkey");

                    b.ToTable("institution", null, t =>
                        {
                            t.HasCheckConstraint("institution_institution_type_check", "institution_type IN ('Home', 'Partner')");
                        });
                });

            modelBuilder.Entity("Loom.Domain.Entities.LearningAgreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ExchangeId")
                        .HasColumnType("integer")
                        .HasColumnName("exchange_id");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<int?>("SignedById")
                        .HasColumnType("integer")
                        .HasColumnName("approved_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("learning_agreement_pkey");

                    b.HasIndex("ExchangeId")
                        .IsUnique()
                        .HasDatabaseName("learning_agreement_exchange_id_key");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("idx_learning_agreement_updated_by");

                    b.HasIndex("SignedById")
                        .HasDatabaseName("idx_learning_agreement_approved_by");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_la_status");

                    b.ToTable("learning_agreement", "exchange", t =>
                        {
                            t.HasCheckConstraint("learning_agreement_status_check", "status IN ('Draft', 'Submitted', 'Approved', 'Rejected')");
                        });
                });

            modelBuilder.Entity("Loom.Domain.Entities.LearningAgreementEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AwardedEcts")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("awarded_ects");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("HomeSlotId")
                        .HasColumnType("integer")
                        .HasColumnName("home_slot_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("LearningAgreementId")
                        .HasColumnType("integer")
                        .HasColumnName("learning_agreement_id");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mode");

                    b.Property<int?>("PartnerCourseId")
                        .HasColumnType("integer")
                        .HasColumnName("partner_course_id");

                    b.HasKey("Id")
                        .HasName("learning_agreement_entry_pkey");

                    b.HasIndex("HomeSlotId")
                        .HasDatabaseName("idx_la_entry_slot");

                    b.HasIndex("LearningAgreementId")
                        .HasDatabaseName("idx_la_entry_la");

                    b.HasIndex("PartnerCourseId")
                        .HasDatabaseName("idx_la_entry_partner_course");

                    b.ToTable("learning_agreement_entry", "exchange", t =>
                        {
                            t.HasCheckConstraint("learning_agreement_entry_mode_check", "mode IN ('AtHome', 'AtExchange', 'AfterExchange')");
                        });
                });

            modelBuilder.Entity("Loom.Domain.Entities.MappingSchemeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AwardedEcts")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("awarded_ects");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EctsGrade")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("ects_grade");

                    b.Property<string>("EnrollmentStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("enrollment_status");

                    b.Property<DateOnly?>("ExamDate")
                        .HasColumnType("date")
                        .HasColumnName("exam_date");

                    b.Property<int>("ExchangeId")
                        .HasColumnType("integer")
                        .HasColumnName("exchange_id");

                    b.Property<int>("HomeSlotId")
                        .HasColumnType("integer")
                        .HasColumnName("home_slot_id");

                    b.Property<string>("HrGrade")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("hr_grade");

                    b.Property<bool?>("IsRecognized")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recognized");

                    b.Property<string>("OriginalGrade")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("original_grade");

                    b.Property<int?>("PartnerCourseId")
                        .HasColumnType("integer")
                        .HasColumnName("partner_course_id");

                    b.Property<int?>("RecognizedAsCourseId")
                        .HasColumnType("integer")
                        .HasColumnName("recognized_as_course_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("mapping_scheme_entry_pkey");

                    b.HasIndex("ExchangeId")
                        .HasDatabaseName("idx_mapping_scheme_entry_exchange");

                    b.HasIndex("HomeSlotId")
                        .HasDatabaseName("idx_mapping_scheme_entry_slot");

                    b.HasIndex("PartnerCourseId")
                        .HasDatabaseName("idx_mapping_scheme_entry_partner_course_id");

                    b.HasIndex("RecognizedAsCourseId")
                        .HasDatabaseName("idx_mapping_scheme_entry_recognized_as_course_id");

                    b.ToTable("mapping_scheme_entry", "exchange", t =>
                        {
                            t.HasCheckConstraint("mapping_scheme_entry_enrollment_status_check", "enrollment_status IN ('Passed', 'NotPassed')");
                        });
                });

            modelBuilder.Entity("Loom.Domain.Entities.PartnerCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuditoryH")
                        .HasColumnType("integer")
                        .HasColumnName("auditory_h");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("Ects")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("ects");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int?>("LabH")
                        .HasColumnType("integer")
                        .HasColumnName("lab_h");

                    b.Property<int?>("LecturesH")
                        .HasColumnType("integer")
                        .HasColumnName("lectures_h");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameHr")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_hr");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("semester");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("course_pkey");

                    b.HasIndex("InstitutionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("idx_partner_course_institution_code");

                    b.ToTable("course", "partner", t =>
                        {
                            t.HasCheckConstraint("course_level_check", "level IN ('Graduate', 'Undergraduate', 'Postgraduate')");

                            t.HasCheckConstraint("course_semester_check", "semester IN ('Winter', 'Summer', 'Both')");
                        });
                });

            modelBuilder.Entity("Loom.Domain.Entities.Recognition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ExchangeId")
                        .HasColumnType("integer")
                        .HasColumnName("exchange_id");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<int?>("SignedById")
                        .HasColumnType("integer")
                        .HasColumnName("approved_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("recognition_pkey");

                    b.HasIndex("ExchangeId")
                        .IsUnique()
                        .HasDatabaseName("recognition_exchange_id_key");

                    b.HasIndex("LastModifiedById")
                        .HasDatabaseName("idx_recognition_updated_by");

                    b.HasIndex("SignedById")
                        .HasDatabaseName("idx_recognition_approved_by");

                    b.ToTable("recognition", "exchange", t =>
                        {
                            t.HasCheckConstraint("recognition_status_check", "status IN ('Draft', 'Submitted', 'Approved', 'Rejected')");
                        });
                });

            modelBuilder.Entity("Loom.Domain.Entities.RecognitionEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EctsGrade")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("ects_grade");

                    b.Property<string>("EnrollmentStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("enrollment_status");

                    b.Property<DateOnly?>("ExamDate")
                        .HasColumnType("date")
                        .HasColumnName("exam_date");

                    b.Property<string>("HrGrade")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("hr_grade");

                    b.Property<bool?>("IsRecognized")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recognized");

                    b.Property<int>("LearningAgreementEntryId")
                        .HasColumnType("integer")
                        .HasColumnName("learning_agreement_entry_id");

                    b.Property<string>("OriginalGrade")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("original_grade");

                    b.Property<int>("RecognitionId")
                        .HasColumnType("integer")
                        .HasColumnName("recognition_id");

                    b.Property<int?>("RecognizedAsCourseId")
                        .HasColumnType("integer")
                        .HasColumnName("recognized_as_course_id");

                    b.HasKey("Id")
                        .HasName("recognition_entry_pkey");

                    b.HasIndex("LearningAgreementEntryId")
                        .IsUnique()
                        .HasDatabaseName("recognition_entry_learning_agreement_entry_id_key");

                    b.HasIndex("RecognitionId")
                        .HasDatabaseName("idx_recognition_entry_recognition");

                    b.HasIndex("RecognizedAsCourseId")
                        .HasDatabaseName("idx_recognition_entry_recognized_as_course_id");

                    b.ToTable("recognition_entry", "exchange");
                });

            modelBuilder.Entity("Loom.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int?>("CoordinatorId")
                        .HasColumnType("integer")
                        .HasColumnName("coordinator_id");

                    b.Property<string>("CoordinatorRequestStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("coordinator_request_status");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("integer")
                        .HasColumnName("institution_id");

                    b.Property<bool>("IsOnboarded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_onboarded");

                    b.Property<string>("Jmbag")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("jmbag");

                    b.Property<string>("Mentor")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mentor");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Student")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("user_pkey");

                    b.HasIndex("CoordinatorId")
                        .HasDatabaseName("idx_user_coordinator");

                    b.HasIndex("Email")
                        .HasDatabaseName("idx_user_email");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("user_external_id_key");

                    b.HasIndex("InstitutionId")
                        .HasDatabaseName("idx_user_institution");

                    b.HasIndex("Jmbag")
                        .IsUnique()
                        .HasDatabaseName("idx_user_jmbag_not_null")
                        .HasFilter("jmbag IS NOT NULL");

                    b.ToTable("user", null, t =>
                        {
                            t.HasCheckConstraint("user_coordinator_request_status_check", "coordinator_request_status IN ('Pending', 'Rejected')");

                            t.HasCheckConstraint("user_role_check", "role IN ('Student', 'Coordinator', 'Admin')");
                        });
                });

            modelBuilder.Entity("Loom.Domain.Entities.CoordinatorWhitelist", b =>
                {
                    b.HasOne("Loom.Domain.Entities.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("coordinator_whitelist_institution_id_fkey");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("Loom.Domain.Entities.Exchange", b =>
                {
                    b.HasOne("Loom.Domain.Entities.User", "Coordinator")
                        .WithMany()
                        .HasForeignKey("CoordinatorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("exchange_coordinator_id_fkey");

                    b.HasOne("Loom.Domain.Entities.HomeProfile", "HomeProfile")
                        .WithMany()
                        .HasForeignKey("HomeProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("exchange_home_profile_id_fkey");

                    b.HasOne("Loom.Domain.Entities.Institution", "PartnerInstitution")
                        .WithMany()
                        .HasForeignKey("PartnerInstitutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("exchange_partner_institution_id_fkey");

                    b.HasOne("Loom.Domain.Entities.User", "Student")
                        .WithMany("StudentExchanges")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("exchange_student_id_fkey");

                    b.Navigation("Coordinator");

                    b.Navigation("HomeProfile");

                    b.Navigation("PartnerInstitution");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Loom.Domain.Entities.ExchangeSnapshot", b =>
                {
                    b.HasOne("Loom.Domain.Entities.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("snapshot_changed_by_id_fkey");

                    b.HasOne("Loom.Domain.Entities.Exchange", "Exchange")
                        .WithMany("Snapshots")
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("snapshot_exchange_id_fkey");

                    b.Navigation("ChangedBy");

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("Loom.Domain.Entities.HomeCourseGroup", b =>
                {
                    b.HasOne("Loom.Domain.Entities.HomeSlotType", "CourseType")
                        .WithMany("CourseGroups")
                        .HasForeignKey("CourseTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("course_group_slot_type_id_fkey");

                    b.Navigation("CourseType");
                });

            modelBuilder.Entity("Loom.Domain.Entities.HomeProfile", b =>
                {
                    b.HasOne("Loom.Domain.Entities.HomeProgram", "Program")
                        .WithMany("Profiles")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("profile_program_id_fkey");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Loom.Domain.Entities.HomeProgram", b =>
                {
                    b.HasOne("Loom.Domain.Entities.Institution", "Institution")
                        .WithMany("HomePrograms")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("program_institution_id_fkey");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("Loom.Domain.Entities.HomeSlot", b =>
                {
                    b.HasOne("Loom.Domain.Entities.HomeCourseGroup", "CourseGroup")
                        .WithMany("Slots")
                        .HasForeignKey("CourseGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("slot_course_group_id_fkey");

                    b.HasOne("Loom.Domain.Entities.HomeCourse", "Course")
                        .WithMany("Slots")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("slot_course_id_fkey");

                    b.HasOne("Loom.Domain.Entities.HomeProfile", "Profile")
                        .WithMany("Slots")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("slot_profile_id_fkey");

                    b.HasOne("Loom.Domain.Entities.HomeSlotType", "SlotType")
                        .WithMany("Slots")
                        .HasForeignKey("SlotTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("slot_slot_type_id_fkey");

                    b.Navigation("Course");

                    b.Navigation("CourseGroup");

                    b.Navigation("Profile");

                    b.Navigation("SlotType");
                });

            modelBuilder.Entity("Loom.Domain.Entities.LearningAgreement", b =>
                {
                    b.HasOne("Loom.Domain.Entities.Exchange", "Exchange")
                        .WithOne("LearningAgreement")
                        .HasForeignKey("Loom.Domain.Entities.LearningAgreement", "ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("learning_agreement_exchange_id_fkey");

                    b.HasOne("Loom.Domain.Entities.User", "LastModifiedByUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("learning_agreement_updated_by_fkey");

                    b.HasOne("Loom.Domain.Entities.User", "SignedByUser")
                        .WithMany()
                        .HasForeignKey("SignedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("learning_agreement_approved_by_fkey");

                    b.Navigation("Exchange");

                    b.Navigation("LastModifiedByUser");

                    b.Navigation("SignedByUser");
                });

            modelBuilder.Entity("Loom.Domain.Entities.LearningAgreementEntry", b =>
                {
                    b.HasOne("Loom.Domain.Entities.HomeSlot", "HomeSlot")
                        .WithMany()
                        .HasForeignKey("HomeSlotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("learning_agreement_entry_home_slot_id_fkey");

                    b.HasOne("Loom.Domain.Entities.LearningAgreement", "LearningAgreement")
                        .WithMany("Entries")
                        .HasForeignKey("LearningAgreementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("learning_agreement_entry_learning_agreement_id_fkey");

                    b.HasOne("Loom.Domain.Entities.PartnerCourse", "PartnerCourse")
                        .WithMany()
                        .HasForeignKey("PartnerCourseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("learning_agreement_entry_partner_course_id_fkey");

                    b.Navigation("HomeSlot");

                    b.Navigation("LearningAgreement");

                    b.Navigation("PartnerCourse");
                });

            modelBuilder.Entity("Loom.Domain.Entities.MappingSchemeEntry", b =>
                {
                    b.HasOne("Loom.Domain.Entities.Exchange", "Exchange")
                        .WithMany()
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("mapping_scheme_entry_exchange_id_fkey");

                    b.HasOne("Loom.Domain.Entities.HomeSlot", "HomeSlot")
                        .WithMany()
                        .HasForeignKey("HomeSlotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("mapping_scheme_entry_home_slot_id_fkey");

                    b.HasOne("Loom.Domain.Entities.PartnerCourse", "PartnerCourse")
                        .WithMany()
                        .HasForeignKey("PartnerCourseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("mapping_scheme_entry_partner_course_id_fkey");

                    b.HasOne("Loom.Domain.Entities.HomeCourse", "RecognizedAsCourse")
                        .WithMany()
                        .HasForeignKey("RecognizedAsCourseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("mapping_scheme_entry_recognized_as_course_id_fkey");

                    b.Navigation("Exchange");

                    b.Navigation("HomeSlot");

                    b.Navigation("PartnerCourse");

                    b.Navigation("RecognizedAsCourse");
                });

            modelBuilder.Entity("Loom.Domain.Entities.PartnerCourse", b =>
                {
                    b.HasOne("Loom.Domain.Entities.Institution", "Institution")
                        .WithMany("PartnerCourses")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("course_institution_id_fkey");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("Loom.Domain.Entities.Recognition", b =>
                {
                    b.HasOne("Loom.Domain.Entities.Exchange", "Exchange")
                        .WithOne("Recognition")
                        .HasForeignKey("Loom.Domain.Entities.Recognition", "ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("recognition_exchange_id_fkey");

                    b.HasOne("Loom.Domain.Entities.User", "LastModifiedByUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("recognition_updated_by_fkey");

                    b.HasOne("Loom.Domain.Entities.User", "SignedByUser")
                        .WithMany()
                        .HasForeignKey("SignedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("recognition_approved_by_fkey");

                    b.Navigation("Exchange");

                    b.Navigation("LastModifiedByUser");

                    b.Navigation("SignedByUser");
                });

            modelBuilder.Entity("Loom.Domain.Entities.RecognitionEntry", b =>
                {
                    b.HasOne("Loom.Domain.Entities.LearningAgreementEntry", "LearningAgreementEntry")
                        .WithOne("RecognitionEntry")
                        .HasForeignKey("Loom.Domain.Entities.RecognitionEntry", "LearningAgreementEntryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("recognition_entry_learning_agreement_entry_id_fkey");

                    b.HasOne("Loom.Domain.Entities.Recognition", "Recognition")
                        .WithMany("Entries")
                        .HasForeignKey("RecognitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("recognition_entry_recognition_id_fkey");

                    b.HasOne("Loom.Domain.Entities.HomeCourse", "RecognizedAsCourse")
                        .WithMany()
                        .HasForeignKey("RecognizedAsCourseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("recognition_entry_recognized_as_course_id_fkey");

                    b.Navigation("LearningAgreementEntry");

                    b.Navigation("Recognition");

                    b.Navigation("RecognizedAsCourse");
                });

            modelBuilder.Entity("Loom.Domain.Entities.User", b =>
                {
                    b.HasOne("Loom.Domain.Entities.User", "Coordinator")
                        .WithMany()
                        .HasForeignKey("CoordinatorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("user_coordinator_id_fkey");

                    b.HasOne("Loom.Domain.Entities.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("user_institution_id_fkey");

                    b.Navigation("Coordinator");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("Loom.Domain.Entities.Exchange", b =>
                {
                    b.Navigation("LearningAgreement");

                    b.Navigation("Recognition");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Loom.Domain.Entities.HomeCourse", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Loom.Domain.Entities.HomeCourseGroup", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Loom.Domain.Entities.HomeProfile", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Loom.Domain.Entities.HomeProgram", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("Loom.Domain.Entities.HomeSlotType", b =>
                {
                    b.Navigation("CourseGroups");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Loom.Domain.Entities.Institution", b =>
                {
                    b.Navigation("HomePrograms");

                    b.Navigation("PartnerCourses");
                });

            modelBuilder.Entity("Loom.Domain.Entities.LearningAgreement", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Loom.Domain.Entities.LearningAgreementEntry", b =>
                {
                    b.Navigation("RecognitionEntry");
                });

            modelBuilder.Entity("Loom.Domain.Entities.Recognition", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Loom.Domain.Entities.User", b =>
                {
                    b.Navigation("StudentExchanges");
                });
#pragma warning restore 612, 618
        }
    }
}
