/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/access/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AccessTokenRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessSessionResponse"];
                    };
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/access/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AccessTokenRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessLinkPreviewResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/access/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AccessTokenRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClaimResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Role?: components["schemas"]["UserRole"];
                    InstitutionId?: number;
                    Registered?: boolean;
                    Page?: number;
                    PageSize?: number;
                    Search?: string;
                    Sort?: string;
                    SortBy?: string;
                    SortDir?: string;
                    SafePage?: number;
                    SafePageSize?: number;
                    Skip?: number;
                    SearchTerm?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserListResponsePage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AdminUpdateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserListResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AdminSetRoleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserListResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/admin/coordinator-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Page?: number;
                    PageSize?: number;
                    Search?: string;
                    Sort?: string;
                    SortBy?: string;
                    SortDir?: string;
                    SafePage?: number;
                    SafePageSize?: number;
                    Skip?: number;
                    SearchTerm?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CoordinatorRequestResponsePage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/coordinator-requests/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["DecideCoordinatorRequestRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/admin/coordinator-whitelist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Page?: number;
                    PageSize?: number;
                    Search?: string;
                    Sort?: string;
                    SortBy?: string;
                    SortDir?: string;
                    SafePage?: number;
                    SafePageSize?: number;
                    Skip?: number;
                    SearchTerm?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CoordinatorWhitelistEntryResponsePage"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AddToWhitelistRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CoordinatorWhitelistEntryResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/coordinator-whitelist/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    email: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    returnUrl?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home-institutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InstitutionResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home-programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HomeProgramResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partner-institutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Country?: string;
                    IncludeDeleted?: boolean;
                    Page?: number;
                    PageSize?: number;
                    Search?: string;
                    Sort?: string;
                    SortBy?: string;
                    SortDir?: string;
                    SafePage?: number;
                    SafePageSize?: number;
                    Skip?: number;
                    SearchTerm?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PartnerInstitutionAdminResponsePage"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PartnerInstitutionRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PartnerInstitutionAdminResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partner-institutions/{institutionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    institutionId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PartnerInstitutionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PartnerInstitutionAdminResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    institutionId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partner-institutions/{institutionId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    institutionId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partner-institutions/{institutionId}/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Semester?: components["schemas"]["ExchangeSemester"];
                    Level?: components["schemas"]["StudyProgramLevel"];
                    IncludeDeleted?: boolean;
                    Page?: number;
                    PageSize?: number;
                    Search?: string;
                    Sort?: string;
                    SortBy?: string;
                    SortDir?: string;
                    SafePage?: number;
                    SafePageSize?: number;
                    Skip?: number;
                    SearchTerm?: string;
                };
                header?: never;
                path: {
                    institutionId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PartnerCourseResponsePage"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    institutionId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PartnerCourseRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PartnerCourseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partner-courses/{courseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PartnerCourseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PartnerCourseResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partner-courses/{courseId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partner-courses/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["MergePartnerCoursesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PartnerCourseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partner-courses/{courseId}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PartnerCourseUsageResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coordinators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CoordinatorOptionResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coordinator/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    AcademicYear?: string;
                    PartnerInstitution?: string;
                    Page?: number;
                    PageSize?: number;
                    Search?: string;
                    Sort?: string;
                    SortBy?: string;
                    SortDir?: string;
                    SafePage?: number;
                    SafePageSize?: number;
                    Skip?: number;
                    SearchTerm?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CoordinatorStudentResponsePage"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PlaceholderStudentRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CoordinatorStudentResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coordinator/students/{studentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    studentId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PlaceholderStudentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CoordinatorStudentResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    studentId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coordinator/students/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StudentFiltersResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchanges/{exchangeGuid}/documents/official": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    lang?: string;
                };
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchanges/{exchangeGuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExchangeResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateExchangeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExchangeResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchanges/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExchangeSummaryResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchanges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateExchangeRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExchangeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchanges/{exchangeGuid}/coordinator-message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateCoordinatorMessageRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExchangeResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/exchanges/{exchangeGuid}/access-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessLinkResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchanges/{exchangeGuid}/access-link/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessLinkResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchanges/{exchangeGuid}/partner-courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Semester?: components["schemas"]["ExchangeSemester"];
                    Level?: components["schemas"]["StudyProgramLevel"];
                    IncludeDeleted?: boolean;
                    Page?: number;
                    PageSize?: number;
                    Search?: string;
                    Sort?: string;
                    SortBy?: string;
                    SortDir?: string;
                    SafePage?: number;
                    SafePageSize?: number;
                    Skip?: number;
                    SearchTerm?: string;
                };
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PartnerCourseResponsePage"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PartnerCourseRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PartnerCourseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchanges/{exchangeGuid}/learning-agreement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LearningAgreementResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SaveLearningAgreementRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LearningAgreementResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchanges/{exchangeGuid}/learning-agreement/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateLaMessageRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LearningAgreementResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/exchanges/{exchangeGuid}/learning-agreement/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateLearningAgreementStatusRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExchangeResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/exchanges/{exchangeGuid}/learning-agreement/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentVersionResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchanges/{exchangeGuid}/learning-agreement/versions/{versionId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                    versionId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RestoreResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchanges/{exchangeGuid}/learning-agreement/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MappingExportDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchanges/{exchangeGuid}/learning-agreement/import/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["MappingExportDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportPreviewResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchanges/{exchangeGuid}/learning-agreement/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["MappingExportDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchanges/{exchangeGuid}/mapping-scheme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MappingSchemeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchanges/{exchangeGuid}/mapping-scheme/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SaveMappingSchemeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MappingSchemeResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchanges/{exchangeGuid}/recognition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecognitionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchanges/{exchangeGuid}/recognition/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecognitionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchanges/{exchangeGuid}/recognition/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SaveGradesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecognitionResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exchanges/{exchangeGuid}/recognition/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateRecognitionStatusRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecognitionResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/exchanges/{exchangeGuid}/recognition/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateRecognitionMessageRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecognitionResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/exchanges/{exchangeGuid}/recognition/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    exchangeGuid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentVersionResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthMeResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateProfileRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthMeResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CompleteOnboardingRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthMeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/coordinator-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthMeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccessLinkPreviewResponse: {
            /** Format: uuid */
            exchangeGuid: string;
            studentName: string;
            partnerInstitutionName: string;
            academicYear: string;
            hasAccess: boolean;
            canClaim: boolean;
        };
        AccessLinkResponse: {
            token: string;
            /** Format: date-time */
            createdAt: string;
        };
        AccessSessionResponse: {
            /** Format: uuid */
            exchangeGuid: string;
        };
        AccessTokenRequest: {
            token: string;
        };
        AddToWhitelistRequest: {
            email: string;
        };
        AdminSetRoleRequest: {
            role: components["schemas"]["UserRole"];
        };
        AdminUpdateUserRequest: {
            name: string;
            jmbag?: string | null;
            mentor?: string | null;
            /** Format: int32 */
            coordinatorId?: number | null;
            /** Format: int32 */
            institutionId?: number | null;
        };
        AgreedEntryResponse: {
            id: string;
            /** Format: int32 */
            homeSlotId: number;
            /** Format: int32 */
            partnerCourseId: number;
            partnerCourseCode: string;
            partnerCourseName: string;
            partnerCourseNameHr: string | null;
            partnerCourseUrl: string | null;
            partnerCourseHours: string | null;
            /** Format: double */
            partnerCourseEcts: number;
            /** Format: int32 */
            homeSlotCourseIsvuCode: number | null;
            homeSlotCourseName: string;
            /** Format: int32 */
            homeSlotCourseGroupIsvuCode: number | null;
            homeSlotCourseGroupName: string;
            homeSlotColor: string;
            /** Format: int32 */
            homeSlotSemester: number;
            /** Format: double */
            awardedEcts: number;
        };
        AuthMeResponse: {
            /** Format: int32 */
            id: number;
            email: string;
            name: string;
            jmbag: string | null;
            mentor: string | null;
            role: components["schemas"]["UserRole"];
            isOnboarded: boolean;
            /** Format: int32 */
            institutionId: number | null;
            institutionName: string | null;
            /** Format: int32 */
            coordinatorId: number | null;
            coordinatorName: string | null;
            coordinatorRequestStatus: components["schemas"]["CoordinatorRequestStatus"] | null;
        };
        ClaimResponse: {
            /** Format: uuid */
            exchangeGuid: string;
        };
        CompleteOnboardingRequest: {
            /** Format: int32 */
            institutionId: number;
            jmbag?: string | null;
            requestCoordinatorRole: boolean;
        };
        CoordinatorOptionResponse: {
            /** Format: int32 */
            id: number;
            name: string;
        };
        CoordinatorRequestResponse: {
            /** Format: int32 */
            id: number;
            name: string;
            email: string;
            institutionName: string | null;
        };
        CoordinatorRequestResponsePage: {
            items: components["schemas"]["CoordinatorRequestResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            hasDeleted: boolean;
        };
        /** @enum {string} */
        CoordinatorRequestStatus: "Pending" | "Rejected";
        CoordinatorStudentResponse: {
            /** Format: int32 */
            id: number;
            name: string;
            jmbag: string | null;
            institutionName: string | null;
            isPlaceholder: boolean;
            /** Format: int32 */
            institutionId: number | null;
            isMyStudent: boolean;
            exchanges: components["schemas"]["ExchangeSummaryResponse"][];
        };
        CoordinatorStudentResponsePage: {
            items: components["schemas"]["CoordinatorStudentResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            hasDeleted: boolean;
        };
        CoordinatorWhitelistEntryResponse: {
            /** Format: int32 */
            id: number;
            email: string;
            /** Format: date-time */
            createdAt: string;
        };
        CoordinatorWhitelistEntryResponsePage: {
            items: components["schemas"]["CoordinatorWhitelistEntryResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            hasDeleted: boolean;
        };
        CourseGradesRequest: {
            /** Format: int32 */
            partnerCourseId: number;
            enrollmentStatus?: string | null;
            originalGrade?: string | null;
            ectsGrade?: string | null;
            hrGrade?: string | null;
            /** Format: date */
            examDate?: string | null;
        };
        CreateExchangeRequest: {
            /** Format: int32 */
            homeProfileId: number;
            /** Format: int32 */
            partnerInstitutionId: number;
            academicYear: string;
            semesterType: string;
            studySemesters: number[];
            /** Format: int32 */
            coordinatorId?: number | null;
            /** Format: int32 */
            targetStudentId?: number | null;
            mentor?: string | null;
        };
        DecideCoordinatorRequestRequest: {
            status: string;
        };
        DocumentChange: {
            type: string;
            /** Format: int32 */
            homeSlotId: number;
            homeSlotLabel: string;
            /** Format: int32 */
            partnerCourseId: number | null;
            partnerCourseCode: string | null;
            partnerCourseName: string | null;
            fields: components["schemas"]["FieldChange"][];
        };
        /** @enum {string} */
        DocumentStatus: "Draft" | "Approved";
        DocumentVersionResponse: {
            /** Format: int32 */
            id: number;
            kind: components["schemas"]["VersionKind"];
            /** Format: int32 */
            versionNo: number | null;
            amendmentLabel: string | null;
            /** Format: date-time */
            createdAt: string;
            createdByName: string | null;
            /** Format: int32 */
            entryCount: number;
            changes: components["schemas"]["DocumentChange"][] | null;
        };
        /** @enum {string} */
        EnrollmentStatus: "Passed" | "NotPassed";
        ExchangeResponse: {
            /** Format: int32 */
            id: number;
            /** Format: uuid */
            guid: string;
            /** Format: int32 */
            studentId: number;
            studentName: string;
            studentJmbag: string | null;
            homeInstitutionName: string;
            homeProgramName: string;
            homeProfile: components["schemas"]["HomeProfileResponse"];
            /** Format: int32 */
            partnerInstitutionId: number;
            partnerInstitutionName: string;
            /** Format: int32 */
            coordinatorId: number | null;
            coordinatorName: string | null;
            mentor: string | null;
            academicYear: string;
            semesterType: components["schemas"]["ExchangeSemester"];
            studySemesters: number[];
            coordinatorMessage: string | null;
            ewpLink: string | null;
            studentIsPlaceholder: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        ExchangeSemester: "Winter" | "Summer" | "Both";
        ExchangeSummaryResponse: {
            /** Format: int32 */
            id: number;
            /** Format: uuid */
            guid: string;
            /** Format: int32 */
            studentId: number;
            studentName: string;
            studentJmbag: string | null;
            partnerInstitutionName: string;
            homeInstitutionName: string;
            homeProgramName: string;
            homeProfileName: string;
            academicYear: string;
            semesterType: components["schemas"]["ExchangeSemester"];
            learningAgreementStatus: components["schemas"]["DocumentStatus"];
            recognitionStatus: components["schemas"]["DocumentStatus"] | null;
            ewpLink: string | null;
        };
        FieldChange: {
            field: string;
            before: string | null;
            after: string | null;
        };
        HomeProfileResponse: {
            /** Format: int32 */
            id: number;
            name: string;
            nameEn: string | null;
        };
        HomeProgramResponse: {
            /** Format: int32 */
            id: number;
            name: string;
            nameEn: string | null;
            level: components["schemas"]["StudyProgramLevel"];
            /** Format: int32 */
            durationSemesters: number;
            profiles: components["schemas"]["HomeProfileResponse"][];
        };
        HomeSlotResponse: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            semester: number;
            /** Format: int32 */
            slotPosition: number;
            /** Format: int32 */
            ects: number;
            /** Format: int32 */
            courseTypeId: number;
            courseTypeName: string;
            courseTypeNameEn: string | null;
            color: string;
            /** Format: int32 */
            courseIsvuCode: number | null;
            courseName: string | null;
            courseNameEn: string | null;
            /** Format: int32 */
            courseGroupIsvuCode: number | null;
            courseGroupName: string | null;
            courseGroupNameEn: string | null;
        };
        ImportContextWarning: {
            field: string;
            fromFile: string;
            inExchange: string;
        };
        ImportPreviewResponse: {
            canApply: boolean;
            blockingCode: string | null;
            blockingMessage: string | null;
            blockingParams: {
                [key: string]: unknown;
            } | null;
            contextWarnings: components["schemas"]["ImportContextWarning"][];
            added: components["schemas"]["ImportRow"][];
            removed: components["schemas"]["ImportRow"][];
            changed: components["schemas"]["ImportRow"][];
            /** Format: int32 */
            unchanged: number;
            skipped: components["schemas"]["ImportSkip"][];
        };
        ImportResult: {
            /** Format: int32 */
            added: number;
            /** Format: int32 */
            removed: number;
            /** Format: int32 */
            changed: number;
            skipped: components["schemas"]["ImportSkip"][];
        };
        ImportRow: {
            /** Format: int32 */
            homeSlotId: number;
            homeSlotLabel: string;
            mode: string;
            /** Format: int32 */
            partnerCourseId: number | null;
            partnerCourseCode: string | null;
            partnerCourseName: string | null;
            /** Format: double */
            awardedEcts: number | null;
            /** Format: double */
            previousEcts: number | null;
            previousMode: string | null;
        };
        ImportSkip: {
            /** Format: int32 */
            homeSlotId: number;
            homeSlotLabel: string;
            partnerCourseCode: string | null;
            reason: string;
        };
        InstitutionResponse: {
            /** Format: int32 */
            id: number;
            name: string;
            nameHr: string | null;
            country: string | null;
            city: string | null;
            erasmusCode: string | null;
        };
        LearningAgreementEntryResponse: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            homeSlotId: number;
            mode: components["schemas"]["SlotMode"];
            /** Format: int32 */
            partnerCourseId: number | null;
            partnerCourseCode: string | null;
            partnerCourseName: string | null;
            partnerCourseNameHr: string | null;
            partnerCourseUrl: string | null;
            /** Format: double */
            awardedEcts: number | null;
            isDeleted: boolean;
            /** Format: int32 */
            amendmentNumber: number | null;
        };
        LearningAgreementEntryUpsertDto: {
            /** Format: int32 */
            homeSlotId: number;
            mode: string;
            /** Format: int32 */
            partnerCourseId: number | null;
            /** Format: double */
            awardedEcts: number | null;
        };
        LearningAgreementResponse: {
            /** Format: int32 */
            exchangeId: number;
            status: components["schemas"]["DocumentStatus"];
            message: string | null;
            slots: components["schemas"]["HomeSlotResponse"][];
            entries: components["schemas"]["LearningAgreementEntryResponse"][];
            /** Format: date-time */
            lastModifiedAt: string | null;
            lastModifiedByName: string | null;
            /** Format: date-time */
            signedAt: string | null;
            signedByName: string | null;
            /** Format: int32 */
            signedCount: number;
            isConcluded: boolean;
            /** Format: date-time */
            concludedAt: string | null;
            concludedByName: string | null;
        };
        MappingExportCourse: {
            /** Format: int32 */
            id: number;
            code: string;
            name: string;
            /** Format: double */
            ects: number;
        };
        MappingExportDto: {
            /** Format: int32 */
            version: number;
            /** Format: date-time */
            exportedAt: string;
            exportedByName: string;
            institution: components["schemas"]["MappingExportInstitution"];
            home: components["schemas"]["MappingExportHomeContext"];
            mappings: components["schemas"]["MappingExportEntry"][];
            format: string | null;
        };
        MappingExportEntry: {
            /** Format: int32 */
            homeSlotId: number;
            homeSlotLabel: string;
            /** Format: int32 */
            homeSlotSemester: number;
            /** Format: int32 */
            homeSlotEcts: number;
            mode: string;
            partnerCourse: components["schemas"]["MappingExportCourse"] | null;
            /** Format: double */
            awardedEcts: number | null;
        };
        MappingExportHomeContext: {
            /** Format: int32 */
            profileId: number;
            profileName: string;
            programName: string;
            institutionName: string;
        };
        MappingExportInstitution: {
            /** Format: int32 */
            id: number;
            name: string;
            erasmusCode: string | null;
        };
        MappingSchemeEntryResponse: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            homeSlotId: number;
            /** Format: int32 */
            partnerCourseId: number | null;
            partnerCourseCode: string;
            partnerCourseName: string;
            partnerCourseNameHr: string | null;
            partnerCourseUrl: string | null;
            partnerCourseHours: string | null;
            /** Format: double */
            partnerCourseEcts: number;
            /** Format: int32 */
            homeSlotCourseIsvuCode: number | null;
            homeSlotCourseName: string;
            /** Format: int32 */
            homeSlotCourseGroupIsvuCode: number | null;
            homeSlotCourseGroupName: string;
            homeSlotColor: string;
            /** Format: int32 */
            homeSlotSemester: number;
            /** Format: double */
            awardedEcts: number;
            enrollmentStatus: components["schemas"]["EnrollmentStatus"] | null;
            originalGrade: string | null;
            ectsGrade: string | null;
            hrGrade: string | null;
            /** Format: date */
            examDate: string | null;
        };
        MappingSchemeResponse: {
            /** Format: int32 */
            exchangeId: number;
            entries: components["schemas"]["MappingSchemeEntryResponse"][];
        };
        MergePartnerCoursesRequest: {
            /** Format: int32 */
            primaryCourseId: number;
            duplicateCourseIds: number[];
        };
        PartnerCourseRequest: {
            code: string;
            name: string;
            nameHr?: string | null;
            /** Format: double */
            ects: number;
            semester: string;
            level: string;
            /** Format: int32 */
            lecturesH?: number | null;
            /** Format: int32 */
            auditoryH?: number | null;
            /** Format: int32 */
            labH?: number | null;
            url?: string | null;
        };
        PartnerCourseResponse: {
            /** Format: int32 */
            id: number;
            code: string;
            name: string;
            nameHr: string | null;
            url: string | null;
            /** Format: double */
            ects: number;
            /** Format: int32 */
            lecturesH: number | null;
            /** Format: int32 */
            auditoryH: number | null;
            /** Format: int32 */
            labH: number | null;
            semester: components["schemas"]["ExchangeSemester"];
            level: components["schemas"]["StudyProgramLevel"];
            isDeleted: boolean;
        };
        PartnerCourseResponsePage: {
            items: components["schemas"]["PartnerCourseResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            hasDeleted: boolean;
        };
        PartnerCourseUsageGroup: {
            programName: string;
            profileName: string;
            /** Format: int32 */
            recognizedAsIsvuCode: number | null;
            recognizedAsName: string;
            isCourseGroup: boolean;
            /** Format: int32 */
            exchangeCount: number;
            /** Format: double */
            totalAwardedEcts: number;
            academicYears: string[];
        };
        PartnerCourseUsageResponse: {
            /** Format: int32 */
            exchangeCount: number;
            groups: components["schemas"]["PartnerCourseUsageGroup"][];
        };
        PartnerInstitutionAdminResponse: {
            /** Format: int32 */
            id: number;
            name: string;
            nameHr: string | null;
            country: string;
            city: string | null;
            erasmusCode: string | null;
            /** Format: int32 */
            courseCount: number;
            isDeleted: boolean;
        };
        PartnerInstitutionAdminResponsePage: {
            items: components["schemas"]["PartnerInstitutionAdminResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            hasDeleted: boolean;
        };
        PartnerInstitutionRequest: {
            name: string;
            nameHr?: string | null;
            country: string;
            city?: string | null;
            erasmusCode?: string | null;
        };
        PlaceholderStudentRequest: {
            name: string;
            jmbag: string;
            /** Format: int32 */
            institutionId: number;
        };
        RecognitionResponse: {
            /** Format: int32 */
            exchangeId: number;
            status: components["schemas"]["DocumentStatus"];
            message: string | null;
            isStarted: boolean;
            /** Format: date-time */
            startedAt: string | null;
            startedByName: string | null;
            canStart: boolean;
            /** Format: int32 */
            agreedVersionNo: number | null;
            agreed: components["schemas"]["AgreedEntryResponse"][];
            /** Format: date-time */
            lastModifiedAt: string | null;
            lastModifiedByName: string | null;
            /** Format: date-time */
            signedAt: string | null;
            signedByName: string | null;
            /** Format: int32 */
            approvedVersionCount: number;
        };
        RestoreMissing: {
            /** Format: int32 */
            homeSlotId: number;
            homeSlotLabel: string;
            partnerCourseCode: string | null;
            partnerCourseName: string | null;
            reason: string;
        };
        RestoreResult: {
            /** Format: int32 */
            entries: number;
            missing: components["schemas"]["RestoreMissing"][];
        };
        SaveGradesRequest: {
            entries: components["schemas"]["CourseGradesRequest"][];
        };
        SaveLearningAgreementRequest: {
            entries: components["schemas"]["LearningAgreementEntryUpsertDto"][];
        };
        SaveMappingSchemeEntryRequest: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            homeSlotId: number;
            /** Format: int32 */
            partnerCourseId?: number | null;
            /** Format: double */
            awardedEcts: number;
            enrollmentStatus?: string | null;
            originalGrade?: string | null;
            ectsGrade?: string | null;
            hrGrade?: string | null;
            /** Format: date */
            examDate?: string | null;
        };
        SaveMappingSchemeRequest: {
            entries: components["schemas"]["SaveMappingSchemeEntryRequest"][];
        };
        SessionResponse: {
            isAuthenticated: boolean;
            user: components["schemas"]["AuthMeResponse"] | null;
        };
        /** @enum {string} */
        SlotMode: "AtHome" | "AtExchange" | "AfterExchange";
        StudentFiltersResponse: {
            academicYears: string[];
            partnerInstitutions: string[];
        };
        /** @enum {string} */
        StudyProgramLevel: "Undergraduate" | "Graduate" | "Postgraduate";
        UpdateCoordinatorMessageRequest: {
            message?: string | null;
        };
        UpdateExchangeRequest: {
            academicYear: string;
            semesterType: string;
            studySemesters: number[];
            /** Format: int32 */
            coordinatorId?: number | null;
            mentor?: string | null;
            ewpLink?: string | null;
        };
        UpdateLaMessageRequest: {
            message?: string | null;
        };
        UpdateLearningAgreementStatusRequest: {
            status: string;
            message?: string | null;
        };
        UpdateProfileRequest: {
            name: string;
            jmbag?: string | null;
            /** Format: int32 */
            institutionId: number;
            mentor?: string | null;
            /** Format: int32 */
            coordinatorId?: number | null;
        };
        UpdateRecognitionMessageRequest: {
            message?: string | null;
        };
        UpdateRecognitionStatusRequest: {
            status: string;
        };
        UserListResponse: {
            /** Format: int32 */
            id: number;
            name: string;
            email: string;
            role: components["schemas"]["UserRole"];
            institutionName: string | null;
            institutionCity: string | null;
            /** Format: int32 */
            institutionId: number | null;
            coordinatorRequestStatus: components["schemas"]["CoordinatorRequestStatus"] | null;
            isOnboarded: boolean;
            jmbag: string | null;
            mentor: string | null;
            /** Format: int32 */
            coordinatorId: number | null;
            coordinatorName: string | null;
        };
        UserListResponsePage: {
            items: components["schemas"]["UserListResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            hasDeleted: boolean;
        };
        /** @enum {string} */
        UserRole: "Student" | "Coordinator" | "Admin";
        /** @enum {string} */
        VersionKind: "Approved" | "Backup";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
