import { api } from './api'

export const documentService = {
  /** The official xlsx, generated by the server from what is saved (LA versions, table 1, results). */
  downloadOfficial: (exchangeId: string, lang: string) =>
    api.get<Blob>(`/api/exchanges/${exchangeId}/documents/official`, { params: { lang }, responseType: 'blob' }),
}
